language: python
sudo: false
dist: trusty
addons:
  apt:
    packages:
     - python-pip

install:
 - pip install xml2rfc

# command to run tests, e.g. python setup.py test
script: make all #upload

env:
 global:
 - GH_REF: github.com/rtcweb-wg/fec.git
 - secure: "Dyu6BRI5Gyidgnshtz4qNvDtXfGLhsoOH9KIyGpk+3RgDYpE2t0uL2D1oWAr7oNbgzHuBpEkd4HaSigs0Yu5UgmQXvhwjBO/ChrleX9g4lVx7qjkOGEz94o6B/FI/ygqmQ819V4CyldZkSYyAJSaL0/OanwuKZ6CejKpCyJYJeo="

